# Deploy the app after integration

name: azure_deploy

on:
  workflow_run:
    workflows: [ 'integrate' ]
    types: [ 'completed' ]

jobs:

  build_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Checkout Source
        uses: actions/checkout@v4

      - name: 🔧 Build Docker Images
        run: docker compose -f docker-compose.yml build

      - name: 🔑 Azure Login w/ Credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
      - name: 🔗 Connect to Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🚀 Deploy to Azure
        run: |
          az webapp config container 
          set --name ${{ secrets.AZURE_BACKEND_WEBAPP_NAME }} 
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} 
          --docker-custom-image-name ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
        run: | 
          az webapp config container 
          set --name ${{ secrets.AZURE_BACKEND_WEBAPP_NAME }} 
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} 
          --docker-custom-image-name ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}